## Библиотека NUMPY

In [1]:
import numpy as np


- генерация массивов со случайными значениями

In [14]:
# 1-мерный массив (array) (вектор строка) горизонтальное измерение, случайные значения целых чисел
# arr_0 = np.random.randint(9) (рандомные числа от 0 до 9)
# arr_0 = np.random.randint(-9,8) (рандомные числа от -9 до 8)
# arr_0 = np.random.randint(-9,8,6) (напишет 6 чисел внутри скобки рандомные от -9 до 8)
arr_0

array([-4, -9, -3,  3, -4, -4, -9, -1,  4,  7, -6, -4,  0,  5, -4, -1, -4,
       -7, -4, -4,  1, -9, -7, -2, -2,  5,  1,  0,  2,  0])

In [20]:
# 2-мерный массив (array) (вектор строка) горизонтальное измерение, случайные значения целых чисел (мин, макс) (колич срок, потом столбцов)
np.random.randint(10, 30, (4,1))

array([[15],
       [15],
       [16],
       [13]])

In [21]:
# 2-мерный массив (матрица) (строка, столбец)
np.random.randint(-3, 20, (4,3))

array([[17, 16,  7],
       [ 8,  2,  2],
       [14, 18,  6],
       [ 6, 15,  4]])

In [22]:
# 3-мерный массив (тензор 3 ранга) (матрица, строка, столбец)
np.random.randint(-3, 20, (4,3,2))

array([[[ 4,  0],
        [ 3,  0],
        [ 9, 19]],

       [[10, 12],
        [13, 18],
        [ 2, 18]],

       [[ 4, 13],
        [16,  9],
        [-2, 12]],

       [[11,  9],
        [13,  9],
        [-1, -3]]])

In [23]:
# 2-мерный массив (матрица) случайных значений с плавающей точкой
# в диапазоне от 0 до 1
np.random.random((3,6))

array([[0.16298644, 0.91097646, 0.46462058, 0.75689186, 0.33784805,
        0.90353161],
       [0.35123514, 0.67900886, 0.40147188, 0.95204632, 0.1392116 ,
        0.64318266],
       [0.37318648, 0.63438697, 0.31417002, 0.22256444, 0.64983266,
        0.91100315]])

In [26]:
# 2-мерный массив (матрица) случайных значений с плавающей точкой
# из нормального (гауссова) распределения
np.random.normal(size=(5,5))

array([[ 0.30569815,  0.12612645,  0.84426262, -0.49162394, -0.0677579 ],
       [ 0.99908397,  0.79554948,  0.34356249, -0.17824073, -1.68580927],
       [-1.0027793 , -1.56804604, -0.46284162,  1.04505051,  0.41487995],
       [-2.23908972, -0.45532284, -0.02850212, -1.44623688,  0.69238143],
       [ 1.72700251, -0.50744731,  1.71318838, -1.47643493,  0.63391971]])

- атрибуты (свойства)

In [30]:
# форма массива
arr_0.shape

(30,)

In [31]:
arr_0 = np.random.normal(size=(5,5))
arr_0

array([[ 0.05508712,  0.04353995, -0.10775843, -0.43793484, -0.08027066],
       [ 0.55144409,  0.62008468, -1.4470736 , -1.48717188,  1.25537679],
       [-0.06009638,  1.15594916, -2.53822764,  0.87151432, -1.74285077],
       [ 0.90878296, -0.94260611, -0.72705668, -0.13350731, -0.72702084],
       [-0.39818943,  0.23989153, -0.35432424, -0.01302682, -0.82645263]])

In [35]:
# тип данных
arr_0.dtype

dtype('float64')

In [36]:
arr_1.dtype

NameError: name 'arr_1' is not defined

In [37]:
# объем занимаемой памяти (в байтах)
arr_0.nbytes

200

In [38]:
# количество всех элементов массива (200/8 байт)
arr_0.size

25

- метод

In [41]:
arr_2 = np.random.randint(-8,2,(3,4))
arr_2

array([[ 0, -7, -8, -6],
       [-7, -8, -7, -3],
       [ 1, -3, -1, -7]])

In [42]:
arr_2.dtype

dtype('int32')

In [43]:
# конвертация типа данных
arr_2.astype("int64")

array([[ 0, -7, -8, -6],
       [-7, -8, -7, -3],
       [ 1, -3, -1, -7]], dtype=int64)

In [44]:
# транспонирование (поворот массива по диагонали)
arr_2.transpose()

array([[ 0, -7,  1],
       [-7, -8, -3],
       [-8, -7, -1],
       [-6, -3, -7]])

In [45]:
# мин из массива
arr_2.min()

-8

In [46]:
# макс из массива
arr_2.max()

1

In [47]:
# сред из массива
arr_2.mean()

-4.666666666666667

- Индексация

In [51]:
arr_3 = np.random.randint(-8,2,(6,6))
arr_3

array([[-3, -1, -4, -4, -4,  0],
       [-7,  1,  0, -2, -2,  1],
       [-4, -7,  1,  1,  1, -2],
       [-1, -3, -5, -1,  0, -6],
       [-7, -3, -7,  0, -8, -1],
       [-7,  0, -1, -3, -5,  1]])

In [59]:
# прямая индексация (сверху вниз, слева направо)
arr_3[:,2]

array([-4,  0,  1, -5, -7, -1])

In [60]:
# обратная индексация
arr_3[-2]

array([-7, -3, -7,  0, -8, -1])

In [61]:
# точечная индексация
arr_3[5,3]

-3

In [62]:
# запись значения
arr_3[5,3] = 100
arr_3

array([[ -3,  -1,  -4,  -4,  -4,   0],
       [ -7,   1,   0,  -2,  -2,   1],
       [ -4,  -7,   1,   1,   1,  -2],
       [ -1,  -3,  -5,  -1,   0,  -6],
       [ -7,  -3,  -7,   0,  -8,  -1],
       [ -7,   0,  -1, 100,  -5,   1]])

- срезы

In [64]:
# срез строк
arr_3[1:3]

array([[-7,  1,  0, -2, -2,  1],
       [-4, -7,  1,  1,  1, -2]])

In [65]:
# срез столбцов
arr_3[:,3:]

array([[ -4,  -4,   0],
       [ -2,  -2,   1],
       [  1,   1,  -2],
       [ -1,   0,  -6],
       [  0,  -8,  -1],
       [100,  -5,   1]])

In [66]:
# срез строк и столбцов
arr_3[:2,3:]

array([[-4, -4,  0],
       [-2, -2,  1]])